[package]
name = "blosc2"
version = "0.1.0"
edition = "2021"

[dependencies]
blosc2-sys = { package = "blosc2-rs-sys", path = "../blosc2-sys" }
libc = "0.2"

[dev-dependencies]
rand = "0.9"
tempfile = "3.13"
